const state = { step: 0, sessionId: null, upload: null, mapping: null, calibration: null, treatment: null, simulation: null, scenarios: [{ name: "Protocol A", days: "7,14,21", doses: "1,1,1" }] };
const stages = ["Data", "Calibration", "Results", "Treatment", "Experiments", "Report"];
const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({"&":"&amp;","<":"&lt;", ">":"&gt;", '"':"&quot;"}[char]));
const api = async (path, options = {}) => { const response = await fetch(path, options); const raw = await response.text(); let body; try { body = raw ? JSON.parse(raw) : {}; } catch { throw new Error(`The server returned HTTP error ${response.status}: ${raw.slice(0, 180)}`); } if (!response.ok) throw new Error(body.detail || `Server error (${response.status})`); return body; };
const select = (label, name, value, options) => `<div class="field"><label>${label}</label><select name="${name}">${options.map((option) => `<option value="${esc(option)}" ${option === value ? "selected" : ""}>${esc(option)}</option>`).join("")}</select></div>`;

function unlockedStep() { if (!state.sessionId || !state.mapping || !state.mapping.ready) return 0; if (!state.calibration) return 1; if (!state.calibration.used) return 2; if (!state.treatment) return 3; if (!state.simulation) return 4; return 5; }
function renderTabs() { $("#tabs").innerHTML = stages.map((name, index) => `<button class="tab ${index === state.step ? "active" : ""} ${index > unlockedStep() ? "locked" : ""}" data-step="${index}"><span class="tab-number">${String(index + 1).padStart(2, "0")}</span>${name}</button>`).join(""); document.querySelectorAll(".tab").forEach((button) => button.addEventListener("click", () => { const step = Number(button.dataset.step); if (step <= unlockedStep()) { state.step = step; render(); } })); }
function setHeader() { $("#stage-kicker").textContent = `STEP ${String(state.step + 1).padStart(2, "0")} / 06`; $("#page-title").textContent = ["Import your data", "Configure calibration", "Review results", "Fit treatment", "Test protocols", "Export work"][state.step]; $("#session-label").textContent = state.sessionId ? `Session ${state.sessionId}` : "No session"; }
function validationMarkup(mapping) { const invalid = (mapping.subjects || []).filter((subject) => !subject.ok && !subject.excluded); return invalid.length ? `<section class="panel validation-panel"><span class="eyebrow">VALIDATION</span><h2>Subjects to fix.</h2><p class="muted">These subjects remain visible, but cannot enter calibration until they are corrected or excluded.</p><div class="table-wrap"><table><thead><tr><th>Subject</th><th>Group</th><th>Points</th><th>Issues</th></tr></thead><tbody>${invalid.map((subject) => `<tr><td>${esc(subject.id)}</td><td>${esc(subject.group)}</td><td>${subject.n_points}</td><td>${esc((subject.why || []).join("; "))}</td></tr>`).join("")}</tbody></table></div></section>` : ""; }
const uiTranslations = [];
function translateInterface() { const appView = $("#app-view"); if (!appView) return; appView.innerHTML = uiTranslations.reduce((html, [source, target]) => html.replaceAll(source, target), appView.innerHTML); }
function render() { renderTabs(); setHeader(); $("#app-view").innerHTML = [dataView, calibrationView, resultsView, treatmentView, experimentsView, reportView][state.step](); if (state.step === 0 && state.mapping?.subjects) $("#app-view").insertAdjacentHTML("beforeend", validationMarkup(state.mapping)); if (state.step === 1) $("#calibration-form").insertAdjacentHTML("beforeend", '<button id="cancel-calibration" class="button cancel-button" type="button" hidden>Cancel job</button>'); if (state.step === 2 && state.calibration) $("#app-view .panel").insertAdjacentHTML("beforeend", fitGridMarkup(state.calibration)); translateInterface(); wireCurrent(); }

function dataView() { const upload = state.upload; const columns = upload?.columns || []; const guess = upload?.mapping_guess || {}; return `<div class="grid"><section class="panel"><span class="eyebrow">01 / SOURCE</span><h2>Your curve, your rules.</h2><p class="muted">CSV/XLSX, long or wide format. The mapping can still be edited before analysis.</p><label class="dropzone"><strong>${upload ? esc(upload.filename) : "Drop a file"}</strong><span>${upload ? "File ready for mapping" : "CSV, XLSX · local data only"}</span><input id="file-input" type="file" accept=".csv,.xlsx,.xls"></label>${upload ? `<form id="mapping-form">${select("Time", "time", guess.time, columns)}${select("Volume", "volume", guess.volume, ["(wide format)", ...columns])}${select("Subject", "subject", guess.subject, ["(single subject)", ...columns])}${select("Group", "group", guess.group, ["(single group)", ...columns])}${select("Time unit", "time_unit", "days", ["days", "hours"])}${select("Volume unit", "volume_unit", "mm3", ["mm3", "cm3"])}<div class="field"><label>Control group</label><input name="control" value="control"></div><div class="field"><label>Subjects to exclude</label><input name="exclude" placeholder="m3,m7"></div><button class="button" type="submit">Validate data →</button></form>` : ""}</section><section class="panel"><div class="preview-head"><div><span class="eyebrow">PREVIEW</span><h2>Instant preview</h2></div>${upload ? `<span class="tag">${upload.columns.length} columns</span>` : ""}</div>${upload ? `<div class="table-wrap"><table><thead><tr>${upload.columns.map((column) => `<th>${esc(column)}</th>`).join("")}</tr></thead><tbody>${upload.rows.map((row) => `<tr>${upload.columns.map((column) => `<td>${esc(row[column])}</td>`).join("")}</tr>`).join("")}</tbody></table></div>` : '<div class="empty"><p>The table will appear here.</p></div>'}</section></div>`; }
function calibrationView() { return `<div class="grid"><section class="panel"><span class="eyebrow">02 / FIT</span><h2>Compare growth laws.</h2><p class="muted">Growth is fitted on the control group, with one T0 per subject.</p><form id="calibration-form"><div class="field"><label>Models to compare</label><div class="model-options">${["exponential", "mendelsohn", "logistic", "bertalanffy", "gompertz", "linear", "surface"].map((model) => `<label><input type="checkbox" name="models" value="${model}" checked> ${model}</label>`).join("")}</div></div><div class="field"><label>T0 strategy</label><select name="t0_strategy"><option value="free">Free: 0.10× to 4×</option><option value="fixed_first_obs">Fixed at first observation</option><option value="narrow_first_obs">Narrow: ±10%</option></select></div><div class="field"><label>Criterion</label><select name="selection_metric"><option value="bic">BIC</option><option value="aicc">AICc</option></select></div><div class="field"><label>Number of starts</label><input name="starts" type="number" min="1" max="20" value="3"></div><div class="field"><label>Maximum iterations</label><input name="maxiter" type="number" min="50" max="2000" value="250"></div><div class="field"><label>Seed</label><input name="seed" type="number" value="42"></div><div class="notice">The progress bar tracks the local job, model by model and starting point by starting point. With 1 or 2 departments, the result is exploratory: use 6 to 8 departments to get a result worth keeping.</div><button class="button" type="submit">Run calibration →</button></form></section><section class="panel"><span class="eyebrow">JOB STATUS</span><h2 id="job-title">Ready.</h2><div id="calibration-status" class="empty"><p>Seven models available, ranked by BIC.</p></div></section></div>`; }
function fitGridMarkup(result) { const curves = result.ranking[0]?.curves || []; const card = (curve) => { const values = [...curve.observed, ...curve.fitted], max = Math.max(...values, 1), min = Math.min(...values, 0), span = Math.max(max - min, 1e-9), points = (valuesToPlot) => valuesToPlot.map((value, index) => `${(index / Math.max(valuesToPlot.length - 1, 1)) * 300},${130 - ((value - min) / span) * 110}`).join(" "); return `<div class="fit-card"><div class="fit-card-head"><b>${esc(curve.subject)}</b><span>${esc(curve.group)}</span></div><svg viewBox="0 0 300 140" role="img" aria-label="Fit of subject ${esc(curve.subject)}"><polyline points="${points(curve.observed)}" fill="none" stroke="var(--sage)" stroke-width="2"/><polyline points="${points(curve.fitted)}" fill="none" stroke="var(--forest)" stroke-width="2" stroke-dasharray="5 4"/></svg><small>observed · fitted</small></div>`; }; return curves.length ? `<div class="fit-section"><div class="preview-head"><div><span class="eyebrow">FIT GRID</span><h3>Curves by subject</h3></div><span class="tag">${curves.length} subjects</span></div><div class="fit-grid">${curves.map(card).join("")}</div></div>` : ""; }
function resultsView() { const result = state.calibration; if (!result) return `<section class="panel empty"><p>Calibration required.</p></section>`; const sentence = result.tie_with.length ? `<b>${esc(result.winner)}</b> wins, but ${result.tie_with.map(esc).join(", ")} is within a ΔBIC of 2: the data do not clearly separate them.` : `<b>${esc(result.winner)}</b> wins clearly; no other model is within 2 BIC points.`; return `<section class="panel"><div class="preview-head"><div><span class="eyebrow">03 / RANKING</span><h2>What the data say.</h2></div><span class="tag">${esc((result.selection_metric || "bic").toUpperCase())} · Δ &lt; 2 = tie</span></div><div class="metric-row"><div class="metric"><small>Selected model</small><strong class="winner">${esc(result.winner)}</strong></div><div class="metric"><small>Tied</small><strong>${result.tie_with.length ? result.tie_with.join(", ") : "None"}</strong></div><div class="metric"><small>T0 strategy</small><strong>${esc(result.t0_strategy || "free")}</strong></div></div><div class="notice">${sentence}</div><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Law</th><th>BIC</th><th>AICc</th><th>ΔBIC</th><th>Akaike weight</th><th>RMSE</th><th>Last point (MAE)</th><th>Action</th></tr></thead><tbody>${result.ranking.map((row, index) => `<tr><td>${index + 1}</td><td><b>${esc(row.model)}</b></td><td>${row.metrics.bic.toFixed(2)}</td><td>${row.metrics.aicc.toFixed(2)}</td><td>${row.delta_bic.toFixed(2)}</td><td>${(row.akaike_weight * 100).toFixed(1)}%</td><td>${row.metrics.rmse.toFixed(3)}</td><td>${row.validation?.enabled ? row.validation.mae.toFixed(3) : "-"}</td><td><button class="button secondary use-model" data-model="${esc(row.model)}" type="button">Use</button></td></tr>`).join("")}</tbody></table></div></section>`; }
function treatmentView() { const treatment = state.treatment; const noneBeaten = treatment ? treatment.winner !== "none" : null; const groups = (state.mapping?.groups || []).filter((group) => group !== state.mapping?.control_group); const resultsPanel = !treatment ? `<div class="notice">The <code>none</code> model is always included as a baseline.</div>` : `<div class="notice">${noneBeaten ? `<b>${esc(treatment.winner)}</b> explains the data better than no treatment (lower BIC than <code>none</code>).` : `No treatment term explains the data better than <code>none</code>: check the dose schedule before concluding there is an effect.`}</div><div class="table-wrap"><table><thead><tr><th>Rank</th><th>Term</th><th>BIC</th><th>ΔBIC</th></tr></thead><tbody>${treatment.ranking.map((row, index) => `<tr><td>${index + 1}</td><td><b>${esc(row.model)}</b></td><td>${row.metrics.bic.toFixed(2)}</td><td>${row.delta_bic.toFixed(2)}</td></tr>`).join("")}</tbody></table></div>`; return `<div class="grid"><section class="panel"><span class="eyebrow">04 / TREATMENT</span><h2>Fit treatment.</h2><p class="muted">The winning growth law remains fixed. The treatment term is fitted on the selected treated group.</p><form id="treatment-form">${select("Treated group", "treated_group", groups[0] || "", groups)}${select("Term", "model", "ED", ["ED", "CD", "AccelED", "MM", "LS", "dePR"])}<div class="field"><label>Dose days</label><input name="days" value="7,14,21"></div><div class="field"><label>Doses</label><input name="doses" value="1,1,1"></div><div class="field"><label>Starts</label><input name="starts" type="number" min="1" max="20" value="3"></div><button class="button" type="submit">Compare treatments →</button></form></section><section class="panel"><span class="eyebrow">GROWTH FIXED</span><h2>${esc(state.calibration?.winner || "-")}</h2><div id="treatment-status" class="empty"><p>Seven terms available, ranked by BIC.</p></div>${resultsPanel}</section></div>`; }
function normalizeScenarioEntry(entry) {
  const name = (entry?.name || "").trim() || `Protocol ${String.fromCharCode(65 + state.scenarios.length)}`;
  const days = (entry?.days || "").split(",").map((value) => value.trim()).filter(Boolean).map(Number);
  const doses = (entry?.doses || "").split(",").map((value) => value.trim()).filter(Boolean).map(Number);
  return { name, days: days.filter((day) => Number.isFinite(day)).map(String).join(","), doses: doses.filter((dose) => Number.isFinite(dose)).map(String).join(",") };
}
function scenarioRowMarkup(scenario, index) {
  return `<div class="scenario-row"><div class="field"><label>Name</label><input name="name" value="${esc(scenario.name)}"></div><div class="field"><label>Days</label><input name="days" value="${esc(scenario.days)}"></div><div class="field"><label>Doses</label><input name="doses" value="${esc(scenario.doses)}"></div><button class="button secondary remove-scenario" type="button" data-index="${index}" aria-label="Remove scenario">Remove</button></div>`;
}
function parseScenarioRows() {
  const rows = [...document.querySelectorAll(".scenario-row")];
  const scenarios = rows.map((row, index) => {
    const name = row.querySelector('[name="name"]').value.trim();
    const days = row.querySelector('[name="days"]').value.split(",").map((value) => value.trim()).filter(Boolean);
    const doses = row.querySelector('[name="doses"]').value.split(",").map((value) => value.trim()).filter(Boolean);
    return { name: name || `Protocol ${String.fromCharCode(65 + index)}`, days, doses };
  });
  const errors = [];
  scenarios.forEach((scenario, index) => {
    if (!scenario.name) errors.push(`Scenario ${index + 1} is missing a name.`);
    if (!scenario.days.length || !scenario.doses.length) errors.push(`Scenario "${scenario.name}" needs at least one dose day and value.`);
    if (scenario.days.length !== scenario.doses.length) errors.push(`Scenario "${scenario.name}" has inconsistent dose days and dose values.`);
    if (scenario.days.some((day) => Number(day) <= 0)) errors.push(`Scenario "${scenario.name}" requires positive dose days.`);
    if (scenario.doses.some((dose) => Number(dose) < 0)) errors.push(`Scenario "${scenario.name}" cannot contain negative doses.`);
  });
  return { scenarios: scenarios.map((scenario) => ({ name: scenario.name, days: scenario.days.join(","), doses: scenario.doses.join(",") })), errors };
}
function experimentsView() { return `<div class="grid"><section class="panel"><span class="eyebrow">05 / SCENARIOS</span><h2>Test the next experiment.</h2><form id="experiment-form"><div class="metric-row experiment-settings"><div class="field"><label>Initial volume (mm³)</label><input name="initial_volume" type="number" min="0.0001" step="0.01" value="0.8"></div><div class="field"><label>Horizon (days)</label><input name="horizon_days" type="number" min="1" step="1" value="60"></div><div class="field"><label>Simulation points</label><input name="n_points" type="number" min="20" max="2000" step="10" value="240"></div></div><div class="generator"><span class="eyebrow">GENERATOR</span><div class="generator-fields"><input id="generator-name" placeholder="Protocol name" value="Generated protocol"><input id="generator-count" type="number" min="1" value="3" placeholder="N doses"><input id="generator-start" type="number" min="0" value="7" placeholder="Start day"><input id="generator-interval" type="number" min="0.1" value="7" placeholder="Interval"><input id="generator-dose" type="number" min="0" step="0.1" value="1" placeholder="Dose"><button class="button secondary" type="button" id="generate-scenario">Generate</button></div></div><div id="scenario-list">${state.scenarios.map(scenarioRowMarkup).join("")}</div><div class="scenario-actions"><button class="button secondary" type="button" id="add-scenario">Add scenario</button></div><button class="button" type="submit">Simulate scenarios →</button></form></section><section class="panel"><span class="eyebrow">OUTCOMES</span><h2>Projected curves.</h2><div id="simulation-status" class="empty"><p>${state.simulation ? "Simulation completed." : "Add a scenario to display the projection."}</p></div>${state.simulation ? chartMarkup(state.simulation) : ""}</section></div>`; }
function chartMarkup(result) { const width = 760, height = 280, colors = ["#698e79", "#9f995b", "#757c5d", "#d3fa99", "#b3d4bd", "#c8b96a", "#4f765f"], all = [result.control, ...result.scenarios.map((scenario) => scenario.values)], max = Math.max(...all.flat(), 1), path = (values) => values.map((value, index) => `${index ? "L" : "M"}${(index / (values.length - 1)) * width},${height - (value / max) * (height - 20)}`).join(" "); return `<div class="chart"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Volume projection"><path d="${path(result.control)}" fill="none" stroke="var(--muted)" stroke-width="2" stroke-dasharray="6 5" aria-label="Simulated control"/>${result.scenarios.map((scenario, index) => `<path d="${path(scenario.values)}" fill="none" stroke="${colors[index % colors.length]}" stroke-width="3" aria-label="${esc(scenario.name)}"/>`).join("")}</svg></div><div class="chart-legend"><span><i class="legend-swatch control-swatch"></i>Control</span>${result.scenarios.map((scenario, index) => `<span><i class="legend-swatch" style="background:${colors[index % colors.length]}"></i>${esc(scenario.name)}</span>`).join("")}</div><div class="metric-row"><div class="metric"><small>Final control</small><strong>${result.control.at(-1).toFixed(2)}</strong></div>${result.scenarios.map((scenario) => `<div class="metric"><small>${esc(scenario.name)}</small><strong class="winner">${scenario.tgi_pct.toFixed(1)}% TGI</strong></div>`).join("")}</div>`; }
function reportView() { return `<section class="panel"><span class="eyebrow">06 / REPORT</span><h2>Traceability flow.</h2><p class="muted">ZIP export with ranking, parameters, curves, scenarios, text report and PNG charts.</p><div class="metric-row"><div class="metric"><small>Session</small><strong>${esc(state.sessionId || "-")}</strong></div><div class="metric"><small>Model</small><strong>${esc(state.calibration?.winner || "-")}</strong></div><div class="metric"><small>Scenarios</small><strong>${state.simulation?.scenarios.length || 0}</strong></div></div><button id="download-report" class="button">Download ZIP →</button></section>`; }

async function pollCalibration(jobId) { let status; do { await new Promise((resolve) => setTimeout(resolve, 200)); status = await api(`/api/jobs/${jobId}`); const pct = status.n_steps ? Math.round((100 * status.step) / status.n_steps) : 0; $("#job-title").textContent = `Job ${status.status} - ${pct}%`; $("#calibration-status").innerHTML = `<div><p>${esc(status.stage || "calibration")}</p><p class="muted">${status.step || 0} / ${status.n_steps || "?"} adjustments (law × start)</p><div class="progress"><i style="width:${pct}%"></i></div></div>`; } while (status.status === "queued" || status.status === "running"); if (status.status !== "done") throw new Error(status.error || (status.status === "cancelled" ? "Calibration was cancelled" : "Calibration failed")); return status.result; }
async function pollJob(jobId, target, label) { let status; do { await new Promise((resolve) => setTimeout(resolve, 200)); status = await api(`/api/jobs/${jobId}`); const pct = status.n_steps ? Math.round((100 * status.step) / status.n_steps) : 0; $(target).innerHTML = `<div><p>${esc(status.stage || label)}</p><p class="muted">${status.step || 0} / ${status.n_steps || "?"} steps</p><div class="progress"><i style="width:${pct}%"></i></div></div>`; } while (status.status === "queued" || status.status === "running"); if (status.status !== "done") throw new Error(status.error || `${label} failed`); return status.result; }
function wireCurrent() {
  const fileInput = $("#file-input");
  if (fileInput) fileInput.addEventListener("change", async () => { const form = new FormData(); form.append("file", fileInput.files[0]); try { state.upload = await api("/api/datasets/upload", { method: "POST", body: form }); state.sessionId = state.upload.source_id; localStorage.setItem("tumor-fit-session", state.sessionId); render(); } catch (error) { alert(error.message); } });
  const mappingForm = $("#mapping-form");
  if (mappingForm) mappingForm.addEventListener("submit", async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(mappingForm)); try { state.mapping = await api("/api/datasets/mapping", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ source_id: state.sessionId, mapping: { time: values.time, volume: values.volume.startsWith("(") ? null : values.volume, subject: values.subject.startsWith("(") ? null : values.subject, group: values.group.startsWith("(") ? null : values.group }, control_group: values.control, time_unit: values.time_unit, volume_unit: values.volume_unit, exclude_subjects: values.exclude.split(",").map((item) => item.trim()).filter(Boolean) }) }); localStorage.setItem("tumor-fit-session", state.sessionId); state.step = state.mapping.ready ? 1 : 0; render(); } catch (error) { alert(error.message); } });
  const calibrationForm = $("#calibration-form");
  if (calibrationForm) calibrationForm.addEventListener("submit", async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(calibrationForm)); const models = [...calibrationForm.querySelectorAll('[name="models"]:checked')].map((input) => input.value); if (!models.length) { alert("Select at least one model"); return; } try { const job = await api("/api/calibration", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ session_id: state.sessionId, models, starts: Number(values.starts), maxiter: Number(values.maxiter), seed: Number(values.seed), selection_metric: values.selection_metric, t0_strategy: values.t0_strategy, count_t0_in_ic: true }) }); const cancelButton = $("#cancel-calibration"); cancelButton.hidden = false; cancelButton.addEventListener("click", () => api(`/api/jobs/${job.job_id}/cancel`, { method: "POST" })); state.calibration = await pollCalibration(job.job_id); state.step = 2; render(); } catch (error) { alert(error.message); } });
  document.querySelectorAll(".use-model").forEach((button) => button.addEventListener("click", async () => { try { await api("/api/calibration/select", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ session_id: state.sessionId, model: button.dataset.model }) }); const selected = state.calibration.ranking.find((row) => row.model === button.dataset.model); state.calibration.ranking = [selected, ...state.calibration.ranking.filter((row) => row.model !== button.dataset.model)]; state.calibration.winner = button.dataset.model; state.calibration.used = true; state.step = 3; render(); } catch (error) { alert(error.message); } }));
  const treatmentForm = $("#treatment-form"); if (treatmentForm) treatmentForm.addEventListener("submit", async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(treatmentForm)); const days = values.days.split(",").map(Number); const doses = values.doses.split(",").map(Number); try { const job = await api("/api/treatment", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ session_id: state.sessionId, treated_group: values.treated_group || null, doses: days.map((day, index) => [day, doses[index]]), starts: Number(values.starts) }) }); state.treatment = await pollJob(job.job_id, "#treatment-status", "treatment"); state.treatment.model = values.model; state.step = 4; render(); } catch (error) { alert(error.message); } });
  const experimentForm = $("#experiment-form"); if (experimentForm) experimentForm.addEventListener("submit", async (event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(experimentForm)); const { scenarios, errors } = parseScenarioRows(); if (errors.length) { alert(errors.join("\n")); return; } state.scenarios = scenarios.map((scenario) => ({ name: scenario.name, days: scenario.days, doses: scenario.doses })); try { const job = await api("/api/experiments/simulate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ session_id: state.sessionId, initial_volume: Number(values.initial_volume), horizon_days: Number(values.horizon_days), n_points: Number(values.n_points), treatment_model: state.treatment?.winner || "ED", treatment_params: state.treatment?.ranking?.[0]?.params || { a: 0.2, b: 0.1 }, scenarios: scenarios.map(({ name, days, doses }) => ({ name, dose_times: days.split(",").map(Number), doses: doses.split(",").map(Number) })) }) }); state.simulation = await pollJob(job.job_id, "#simulation-status", "simulation"); render(); } catch (error) { alert(error.message); } });
  const generateScenario = $("#generate-scenario"); if (generateScenario) generateScenario.addEventListener("click", () => { const count = Number($("#generator-count").value); const start = Number($("#generator-start").value); const interval = Number($("#generator-interval").value); const dose = Number($("#generator-dose").value); const name = $("#generator-name").value.trim() || `Protocol ${String.fromCharCode(65 + state.scenarios.length)}`; state.scenarios = [...document.querySelectorAll(".scenario-row")].map((row) => ({ name: row.querySelector('[name="name"]').value, days: row.querySelector('[name="days"]').value, doses: row.querySelector('[name="doses"]').value })); state.scenarios.push({ name, days: Array.from({ length: count || 1 }, (_, index) => (start + index * interval).toString()).join(","), doses: Array.from({ length: count || 1 }, () => dose).join(",") }); render(); });
  const addScenario = $("#add-scenario"); if (addScenario) addScenario.addEventListener("click", () => { state.scenarios = [...document.querySelectorAll(".scenario-row")].map((row) => ({ name: row.querySelector('[name="name"]').value, days: row.querySelector('[name="days"]').value, doses: row.querySelector('[name="doses"]').value })); state.scenarios.push({ name: `Protocol ${String.fromCharCode(65 + state.scenarios.length)}`, days: "7,21", doses: "0.7,0.7" }); render(); });
  document.querySelectorAll(".remove-scenario").forEach((button) => button.addEventListener("click", () => { const index = Number(button.dataset.index); state.scenarios = [...document.querySelectorAll(".scenario-row")].map((row) => ({ name: row.querySelector('[name="name"]').value, days: row.querySelector('[name="days"]').value, doses: row.querySelector('[name="doses"]').value })); state.scenarios.splice(index, 1); if (!state.scenarios.length) state.scenarios.push({ name: "Protocol A", days: "7", doses: "1" }); render(); }));
  const download = $("#download-report"); if (download) download.addEventListener("click", () => { window.location.href = `/api/export/${encodeURIComponent(state.sessionId)}`; });
}

const themeToggle = $("#theme-toggle");
const savedTheme = localStorage.getItem("tumor-fit-theme");
if (savedTheme === "dark") document.documentElement.classList.add("dark");
function updateThemeLabel() { const dark = document.documentElement.classList.contains("dark"); themeToggle.textContent = dark ? "☀" : "☾"; themeToggle.title = dark ? "Enable light mode" : "Enable dark mode"; themeToggle.setAttribute("aria-label", themeToggle.title); }
themeToggle.addEventListener("click", () => { document.documentElement.classList.toggle("dark"); localStorage.setItem("tumor-fit-theme", document.documentElement.classList.contains("dark") ? "dark" : "light"); updateThemeLabel(); });
updateThemeLabel();
render();
async function restoreSession() { const sessionId = localStorage.getItem("tumor-fit-session"); if (!sessionId) return; try { const saved = await api(`/api/sessions/${encodeURIComponent(sessionId)}`); state.sessionId = saved.session_id; state.upload = { source_id: saved.session_id, filename: saved.filename, ...saved.preview }; if (saved.mapping) state.mapping = { ...saved.mapping, groups: saved.groups, control_group: saved.control_group, subjects: saved.validation }; state.calibration = saved.calibration; if (state.calibration) state.calibration.used = Boolean(state.calibration.selected_model); state.treatment = saved.treatment; state.simulation = saved.simulation; state.step = state.simulation ? 5 : state.treatment ? 4 : state.calibration?.used ? 3 : state.calibration ? 2 : state.mapping ? 1 : 0; render(); } catch { localStorage.removeItem("tumor-fit-session"); } }
restoreSession();
